# Generated by Django 4.2.6 on 2025-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BogieChecksheetForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "BogieNumber",
                    models.CharField(max_length=100, unique="Truename=Bogie No"),
                ),
                ("Malker & Year Built", models.CharField(max_length=100)),
                ("Incoming Div. & Date", models.DateField()),
                ("Deflict of Components (if any)", models.JSONField()),
                ("Date of IOH", models.DateField()),
                ("inspectionBy", models.CharField(max_length=100)),
                ("inspectionDate", models.DateField()),
                ("bogieDetails", models.JSONField()),
                ("bogieChecksheet", models.JSONField()),
                ("bmbcChecksheet", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="WheelSpecificationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submittedDate",
                    models.DateField(auto_created=True, auto_now_add=True),
                ),
                ("Form Number", models.TextField(max_length=100, unique=True)),
                ("Submitted By", models.TextField(max_length=100)),
                ("Tread Diameter (New)", models.TextField(max_length=100)),
                ("Last Shop Issue Size", models.TextField(max_length=100)),
                ("Condemning Dia.", models.TextField(max_length=100)),
                ("Wheel Gauge", models.TextField(max_length=100)),
                ("Variation Same Axle", models.IntegerField(default=5)),
                ("Variation Same Bogie", models.IntegerField(default=10)),
                ("Variation Same Coach", models.IntegerField(default=15)),
                ("Wheel Profile", models.TextField(max_length=100)),
                ("Intermediate WWP", models.TextField(max_length=100)),
                ("Bearing Seat Diameter", models.TextField(max_length=100)),
                ("Roller Bearing Bore Dia.", models.CharField(max_length=100)),
                ("Roller Bearing Width", models.TextField(max_length=100)),
                ("Axle Box Housing Bore Dia.", models.TextField(max_length=100)),
                ("Wheel Disc Width", models.TextField(max_length=100)),
            ],
        ),
    ]
