# Generated by Django 4.2.6 on 2025-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BogieChecksheet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "BogieNumber",
                    models.CharField(max_length=100, unique="Truename=Bogie No"),
                ),
                ("Malker & Year Built", models.CharField(max_length=100)),
                ("Incoming Div. & Date", models.DateField()),
                ("Deflict of Components (if any)", models.JSONField()),
                ("Date of IOH", models.DateField()),
                (
                    "Bogie Field Condition",
                    models.CharField(
                        choices=[
                            ("Overaged", "Overaged"),
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("OtherBogieField", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Blaster",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Blaster Suspension Bracket",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Lower Spring Seat",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Axle Guide",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Axle Guide Assembly",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Protective Tubes",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Anchor Link",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Side Bearer",
                    models.CharField(
                        choices=[
                            ("Cracked", "Cracked"),
                            ("Worn  out", "Worn out"),
                            ("Good", "Good"),
                            ("otherBlaster", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Cylinder Body & Dome Cover",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Piston Trunnion Body",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Adjusting Tube and Screw",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Plunger Spring",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Tree Bolt Hex Nut",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Pawl and Pawl Spring",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
                (
                    "Dust Excluder",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Worn out", "Worn out"),
                            ("Damaged", "Damaged"),
                            ("OtherBMBCChecksheet", "Other"),
                        ],
                        default="Good",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WheelSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tread Diameter (New)", models.CharField(max_length=100)),
                ("Last Shop Issue Size", models.CharField(max_length=100)),
                ("Condemning Dia.", models.CharField(max_length=100)),
                ("Wheel Gauge", models.CharField(max_length=100)),
                ("Variation Same Axle", models.IntegerField(default=5)),
                ("Variation Same Bogie", models.IntegerField(default=10)),
                ("Variation Same Coach", models.IntegerField(default=15)),
                ("Wheel Profile", models.CharField(max_length=100)),
                ("Intermediate WWP", models.CharField(max_length=100)),
                ("Bearing Seat Diameter", models.CharField(max_length=100)),
                ("Roller Bearing Diameter", models.CharField(max_length=100)),
                ("Roller Bearing Bore Dia.", models.CharField(max_length=100)),
                ("Roller Bearing Width", models.TextField(max_length=100)),
                ("Axle Box Housing Bore Dia.", models.TextField(max_length=100)),
                ("Wheel Disc Width", models.TextField(max_length=100)),
            ],
        ),
    ]
