# Generated by Django 4.2.6 on 2025-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="id",
            field=models.CharField(
                auto_created=True, max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
