# Generated by Django 4.2.6 on 2025-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_alter_bogiechecksheet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="Date of IOH",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="Incoming Div. & Date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
