# Generated by Django 4.2.6 on 2025-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_alter_bogiechecksheet_date_of_ioh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="Date of IOH",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bogiechecksheet",
            name="Incoming Div. & Date",
            field=models.DateField(),
        ),
    ]
