# Generated by Django 4.2.6 on 2025-07-28 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0004_alter_bogiechecksheet_date_of_ioh_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="BogieNumber",
            new_name="bogie_number",
        ),
    ]
