# Generated by Django 4.2.6 on 2025-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0005_rename_bogienumber_bogiechecksheet_bogie_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Adjusting Tube and Screw",
            new_name="adjusting_tubeand_screw",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Anchor Link",
            new_name="anchor_link",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Axle Guide",
            new_name="axle_guide",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Axle Guide Assembly",
            new_name="axle_guide_assembly",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Blaster",
            new_name="blaster",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Blaster Suspension Bracket",
            new_name="blaster_suspension_bracket",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Bogie Field Condition",
            new_name="bogie_field_codition",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Cylinder Body & Dome Cover",
            new_name="cylinder_body_dome_cover",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Date of IOH",
            new_name="date_of_IOH",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Deflict of Components (if any)",
            new_name="deflict_of_components",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Dust Excluder",
            new_name="dust_excluder",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Incoming Div. & Date",
            new_name="incoming_div_date",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Lower Spring Seat",
            new_name="lower_spring_seat",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Malker & Year Built",
            new_name="maker_year_built",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Pawl and Pawl Spring",
            new_name="pawl_pawl_spring",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Piston Trunnion Body",
            new_name="piston_trunnion_body",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Plunger Spring",
            new_name="plunger_spring",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Protective Tubes",
            new_name="protective_tubes",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Side Bearer",
            new_name="side_bearer",
        ),
        migrations.RenameField(
            model_name="bogiechecksheet",
            old_name="Tree Bolt Hex Nut",
            new_name="tree_bolt_hexNut",
        ),
    ]
